site_name: Planky

theme:
  name: readthedocs

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          inherited_members: true
          docstring_style: sphinx
          show_source: false